version: '3.9'
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  service:
    image: user-service:latest
    ports:
      - "50051:50051"
    environment:
      MONGO_HOST: "db"
    depends_on:
      - db
  
volumes:
  mongo-data: {}