# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0buserservice\"3\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"0\n\x0eGetUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"7\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t2\x9d\x01\n\x0bUserService\x12I\n\nCreateUser\x12\x1e.userservice.CreateUserRequest\x1a\x19.userservice.UserResponse\"\x00\x12\x43\n\x07GetUser\x12\x1b.userservice.GetUserRequest\x1a\x19.userservice.UserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=27
  _globals['_CREATEUSERREQUEST']._serialized_end=78
  _globals['_GETUSERREQUEST']._serialized_start=80
  _globals['_GETUSERREQUEST']._serialized_end=128
  _globals['_USERRESPONSE']._serialized_start=130
  _globals['_USERRESPONSE']._serialized_end=185
  _globals['_USERSERVICE']._serialized_start=188
  _globals['_USERSERVICE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
